# Generated by Django 3.0.4 on 2020-12-21 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20201220_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Author')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Project')),
            ],
            options={
                'verbose_name': 'project has author',
                'verbose_name_plural': 'project has authors',
                'db_table': 'project_has_author',
                'ordering': ['project', 'author'],
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='authors',
            field=models.ManyToManyField(through='database.ProjectAuthor', to='database.Author'),
        ),
    ]
