# Generated by Django 3.0.4 on 2020-12-22 05:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20201222_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 22, 5, 33, 56, 626882, tzinfo=utc)),
        ),
    ]
