# Generated by Django 3.0.4 on 2020-12-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20201222_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='message',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
