# Generated by Django 3.0.4 on 2020-12-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_commit_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='message',
            field=models.TextField(),
        ),
    ]
