# Generated by Django 3.0.4 on 2021-01-05 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_commit_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('github_username', models.CharField(max_length=64, null=True)),
                ('gitlab_username', models.CharField(max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'people',
                'db_table': 'person',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='commit',
            name='branch',
            field=models.CharField(default='master', max_length=64),
        ),
        migrations.AddField(
            model_name='project',
            name='fork_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Project'),
        ),
        migrations.CreateModel(
            name='PersonAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Author')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Person')),
            ],
            options={
                'verbose_name': 'person has author',
                'verbose_name_plural': 'person has authors',
                'db_table': 'person_has_auhtor',
                'ordering': ['id'],
            },
        ),
    ]
