# Generated by Django 3.0.4 on 2021-02-02 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20210105_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='fork_of',
        ),
    ]
