# Generated by Django 3.0.4 on 2021-02-02 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_remove_project_fork_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='fork_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Project'),
        ),
    ]
