# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-02-13 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'author',
                'verbose_name_plural': 'authors',
                'db_table': 'author',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=128)),
                ('datetime', models.DateTimeField()),
                ('message', models.TextField()),
                ('branch', models.CharField(default='master', max_length=128)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Author')),
            ],
            options={
                'verbose_name': 'commit',
                'verbose_name_plural': 'commits',
                'db_table': 'commit',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Diff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FilePathField()),
                ('language', models.CharField(max_length=64)),
                ('body', models.TextField()),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Commit')),
            ],
            options={
                'verbose_name': 'diff',
                'verbose_name_plural': 'diffs',
                'db_table': 'diff',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('github_username', models.CharField(max_length=64, null=True)),
                ('gitlab_username', models.CharField(max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'people',
                'db_table': 'person',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PersonAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Author')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Person')),
            ],
            options={
                'verbose_name': 'person has author',
                'verbose_name_plural': 'person has authors',
                'db_table': 'person_has_auhtor',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField()),
                ('name', models.CharField(max_length=64)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'db_table': 'project',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Author')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Project')),
            ],
            options={
                'verbose_name': 'project has author',
                'verbose_name_plural': 'project has authors',
                'db_table': 'project_has_author',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='authors',
            field=models.ManyToManyField(through='database.ProjectAuthor', to='database.Author'),
        ),
        migrations.AddField(
            model_name='project',
            name='fork_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Project'),
        ),
        migrations.AddField(
            model_name='commit',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Project'),
        ),
    ]
