# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-02-15 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='branch',
            field=models.CharField(default='master', max_length=256),
        ),
    ]
