# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-02-21 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20210215_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diff',
            name='file_path',
            field=models.FilePathField(max_length=256),
        ),
    ]
