# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-02-24 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20210222_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='branch',
            field=models.CharField(default='master', max_length=1024),
        ),
    ]
