# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-06-21 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_auto_20210526_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='has_github',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='has_gitlab',
            field=models.BooleanField(default=False),
        ),
    ]
