# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-08-17 03:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_auto_20210817_0256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventpages',
            old_name='commit',
            new_name='page',
        ),
        migrations.RenameField(
            model_name='eventpages',
            old_name='event_payload',
            new_name='payload',
        ),
    ]
