# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-08-17 04:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0027_remove_eventpayload_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventpayload',
            old_name='before',
            new_name='before_sha',
        ),
        migrations.RenameField(
            model_name='eventpayload',
            old_name='head',
            new_name='head_sha',
        ),
    ]
