# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-08-17 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0028_auto_20210817_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpayload',
            name='action',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
