# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-08-17 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0029_auto_20210817_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpayload',
            name='push_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
