# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-08-17 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0030_auto_20210817_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='api_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='eventpayload',
            name='distinct_size',
            field=models.BigIntegerField(null=True),
        ),
    ]
