# Generated by Django 3.2.6 on 2021-09-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0033_auto_20210917_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='username',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
