# Generated by Django 3.2.6 on 2022-04-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0034_alter_author_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='diff',
            name='header',
            field=models.TextField(null=True),
        ),
    ]
