# Generated by Django 4.0.4 on 2022-06-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0038_projectrole_project'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='projectrole',
            constraint=models.UniqueConstraint(fields=('user', 'project'), name='unique_user_project_assignment'),
        ),
    ]
