# Generated by Django 4.0.4 on 2022-06-20 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0040_projectrole_unique_user_project_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeerCATUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_login', models.CharField(max_length=200)),
                ('gihtub_email', models.EmailField(max_length=200)),
                ('personal_email', models.EmailField(max_length=200)),
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
