# Generated by Django 4.0.4 on 2022-06-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0041_alter_projectrole_id_meercatuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meercatuser',
            old_name='gihtub_email',
            new_name='GitHub_email',
        ),
        migrations.RenameField(
            model_name='meercatuser',
            old_name='github_login',
            new_name='GitHub_login',
        ),
        migrations.RenameField(
            model_name='meercatuser',
            old_name='django_user',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='meercatuser',
            name='personal_email',
        ),
    ]
