# Generated by Django 4.0.4 on 2022-06-20 22:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0042_rename_gihtub_email_meercatuser_github_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeerCATUser',
            new_name='GitHubCredentials',
        ),
        migrations.AlterModelOptions(
            name='githubcredentials',
            options={'verbose_name': 'GitHub Credential'},
        ),
    ]
