# Generated by Django 4.0.4 on 2022-06-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0043_rename_meercatuser_githubcredentials_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='githubcredentials',
            options={'verbose_name': 'GitHub Credentials'},
        ),
    ]
