# Generated by Django 4.0.4 on 2022-06-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0044_alter_githubcredentials_options_alter_projectrole_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubcredentials',
            old_name='GitHub_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='githubcredentials',
            old_name='GitHub_login',
            new_name='login',
        ),
    ]
