# Generated by Django 4.0.4 on 2022-06-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0045_rename_github_email_githubcredentials_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrole',
            name='whitelist',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
