# Generated by Django 4.0.4 on 2022-07-05 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0046_projectrole_whitelist_alter_projectrole_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Email sent'), (1, 'Comment left'), (2, 'No email sent')], default=0, null=True)),
                ('pending', models.BooleanField(default=True)),
                ('notified_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.pullrequest')),
            ],
        ),
    ]
