# Generated by Django 4.0.4 on 2022-07-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0050_eventlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
