# Generated by Django 4.0.4 on 2022-07-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0051_eventlog_json_alter_eventlog_view_args_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='view_args',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='view_kwargs',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
