# Generated by Django 4.0.4 on 2022-07-21 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0052_alter_eventlog_view_args_alter_eventlog_view_kwargs'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='pull_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.pullrequest'),
        ),
    ]
