# Generated by Django 4.0.7 on 2022-09-28 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0058_alter_profile_gh_email_alter_profile_gl_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('supportType', models.CharField(choices=[('BUG', 'Encountered bug'), ('FEEDBACK', 'User feedback')], max_length=64)),
                ('relatedURL', models.URLField(verbose_name='Related URL')),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
