# Generated by Django 4.0.7 on 2022-09-28 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0059_supportsubmission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportsubmission',
            old_name='message',
            new_name='description',
        ),
    ]
