# Generated by Django 4.0.7 on 2022-10-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0060_rename_message_supportsubmission_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportsubmission',
            name='relatedURL',
        ),
        migrations.AddField(
            model_name='supportsubmission',
            name='feature',
            field=models.CharField(choices=[('GENERAL', 'General issue or feedback'), ('LOGIN', 'Logging in to MeerCAT'), ('LOGOUT', 'Logging out of MeerCAT'), ('PRA', 'Pull request assitant'), ('HOME', 'Home page'), ('SUPPORT', 'Supprt page')], default='GENERAL', max_length=64, verbose_name='Site feature'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportsubmission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='support/'),
        ),
    ]
