# Generated by Django 4.0.7 on 2022-10-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0062_alter_supportsubmission_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='event_type',
            field=models.CharField(choices=[('DEBUGGING', 'Debugging log'), ('FEAT', 'Feature used'), ('ERR', 'Error'), ('EMAIL', 'Email sent'), ('EMAIL_FAIL', 'Failed to send email'), ('NOTIFICATION', 'Notification sent'), ('NO_NOTIFICATION', 'No notification sent'), ('NOTIFICATION_FAIL', 'Failed to send notification')], max_length=25),
        ),
    ]
