# Generated by Django 4.0.7 on 2023-01-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0065_filemetric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemetric',
            name='branch',
            field=models.CharField(max_length=256),
        ),
        migrations.AddConstraint(
            model_name='filemetric',
            constraint=models.UniqueConstraint(fields=('project', 'metric_type', 'file_path', 'branch'), name='unique_file_metric'),
        ),
    ]
