# Generated by Django 4.0.7 on 2023-01-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0067_alter_filemetric_result_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='complete_ignore_extensions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
