# Generated by Django 4.0.7 on 2023-04-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0070_remove_project_doctype_remove_project_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemetric',
            name='metric_type',
            field=models.CharField(choices=[('DOCUMENTATION', 'Documentation'), ('LINTING', 'Linting'), ('DEVELOPERS', 'Developers'), ('BUSFACTOR', 'Busfactor')], max_length=25),
        ),
    ]
