# Generated by Django 4.1.7 on 2023-05-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0072_remove_profile_subscriptions_profile_watchlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="watchlist",
        ),
        migrations.AddField(
            model_name="profile",
            name="subscriptions",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
