# Generated by Django 4.1.7 on 2023-06-30 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0074_alter_profile_subscriptions"),
    ]

    operations = [
        migrations.CreateModel(
            name="PRAFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thumbs", models.BooleanField(verbose_name="Thumbs up")),
                (
                    "message",
                    models.TextField(blank=True, verbose_name="Feedback message"),
                ),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.CharField(
                        blank="False", max_length=200, verbose_name="Feedback type"
                    ),
                ),
                (
                    "filepath",
                    models.CharField(max_length=400, verbose_name="File path"),
                ),
                (
                    "pullrequest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.pullrequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
