# Generated by Django 4.0.7 on 2023-08-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0075_prafeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code_quality_library',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='documentation_library',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
