# Generated by Django 4.0.7 on 2023-10-16 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0076_project_code_quality_library_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemetric',
            name='pull_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.pullrequest'),
        ),
        migrations.AlterField(
            model_name='filemetric',
            name='metric_type',
            field=models.CharField(choices=[('DOCUMENTATION', 'Documentation'), ('LINTING', 'Linting'), ('DEVELOPERS', 'Developers'), ('BUSFACTOR', 'Busfactor'), ('LLM', 'LLM')], max_length=25),
        ),
    ]
