# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-05-21 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_pullrequest_merged_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='pr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.PullRequest'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Issue'),
        ),
    ]
