# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-08-17 02:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_auto_20210816_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventactor',
            old_name='name',
            new_name='login',
        ),
        migrations.RenameField(
            model_name='eventrepo',
            old_name='login',
            new_name='name',
        ),
    ]
