# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-08-17 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_auto_20210817_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventrepo',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='eventrepo',
            name='gravatar_id',
        ),
        migrations.AddField(
            model_name='eventactor',
            name='avatar_url',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventactor',
            name='gravatar_id',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
    ]
