# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-08-17 03:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0026_auto_20210817_0333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpayload',
            name='comment',
        ),
    ]
