# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-08-17 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0031_auto_20210817_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.Project'),
            preserve_default=False,
        ),
    ]
