# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-05-19 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_auto_20210509_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuecomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='issuecomment',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='pullrequestcomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='pullrequestcomment',
            name='pr',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='pullrequest',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Issue'),
        ),
        migrations.AddField(
            model_name='comment',
            name='pr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.PullRequest'),
        ),
        migrations.DeleteModel(
            name='IssueComment',
        ),
        migrations.DeleteModel(
            name='PullRequestComment',
        ),
    ]
