# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-06-21 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_auto_20210621_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='gitlab_last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
