# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-07-30 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_auto_20210621_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'issue tag',
                'verbose_name_plural': 'issue tags',
                'db_table': 'issue_tag',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PullRequestIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.IssueTag')),
                ('pr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.PullRequest')),
            ],
            options={
                'verbose_name': 'pull request has issue',
                'verbose_name_plural': 'pull request has issues',
                'db_table': 'pr_has_issue',
                'ordering': ['id'],
            },
        ),
    ]
